### ISSUE TITLE
plugin works but spams the server console

### ISSUE THREAD

**Issue by pbanj** [Allstreamer/TwerkItAll#1]
players can twerk and it will work, but the console spams this every time they twerk
paper 1.20.2

![image](https://github.com/Allstreamer/TwerkItAll/assets/17306233/f014dde9-baa2-4402-ad8a-8a0d8251f514)

**Comment by Allstreamer** [comment]
Fixed in 9bebed5d3e542cb6d9a0886875de735ccc4d0236, going to push a new build to Modrinth in a minute!

**Comment by pbanj** [comment]
Sweet, thank you
